# Generated by Django 3.2.7 on 2021-10-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
