# Generated by Django 3.2.7 on 2021-10-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='age',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
